package bmcmonitoring

// Here we will save the names of the labels.

// Prefixes
const (
	PrefixEthernetRMON         = "habana_bmc_ethernet_rmon"
	PrefixHbm                  = "habana_bmc_hbm"
	PrefixCTemperature         = "habana_bmc_ctemperature"
	PrefixDirect               = "habana_bmc_direct"
	PrefixSecurity             = "habana_bmc_security"
	PrefixInfo                 = "habana_bmc_info"
	PrefixSensorCurrent        = "habana_bmc_sensor_current"
	PrefixSensorVoltage        = "habana_bmc_sensor_voltage"
	PrefixSensorVoltageMonitor = "habana_bmc_sensor_voltage_monitor"
	PrefixSensorTemperature    = "habana_bmc_sensor_temperature"
	PrefixPower                = "habana_bmc_power"
	PrefixFrequency            = "habana_bmc_frequency"
	PrefixStatus               = "habana_bmc_status"
	PrefixPcieInfo             = "habana_bmc_pcie_info"
	PrefixEthernetStatus       = "habana_bmc_ethernet_status"
	PrefixEthernetInfo         = "habana_bmc_ethernet_info"
	PrefixTemperature          = "habana_bmc_temperature"
	PrefixAlerts               = "habana_bmc_alerts"
	PrefixRMA                  = "habana_bmc_rma"
	PrefixLaneInfo             = "habana_bmc_lane_info"
	PrefixBMCState             = "habana_bmc_state"
)

// Direct metric names.
const (
	DirectMetricPCIeVendorID     = "PCIe Vendor ID"
	DirectMetricASICSerialNumber = "ASIC Serial Number"
	DirectMetricFWVersionMajor   = "FW Version Major"
	DirectMetricFWVersionMinor   = "FW Version Minor"
	DirectMetricFWVersionPatch   = "FW Version Patch"
	DirectMetricCoreVDD          = "Core VDD"
	DirectMetricHBMVDDq          = "HBM VDDq"
	DirectMetricV12              = "12V"
	DirectMetricApiVersion       = "Api version"
	DirectMetricOSStage          = "OS Stage"
	DirectMetricIBAccessState    = "IB Access State"
	DirectMetricOOBAccessState   = "OOB Access State"
)

// Ethernet info metric names.
const (
	EthernetInfoMetricSerDesAvailability   = "SerDes Availability"
	EthernetInfoMetricPortMaxSpeed         = "Port Max Speed"
	EthernetInfoMetricANLTStatus           = "ANLT Status"
	EthernetInfoMetricNumberOfLanes        = "Number of Lanes"
	EthernetInfoMetricNumberOfLinks        = "Number of Links"
	EthernetInfoMetricLinkSpeed            = "Link Speed"
	EthernetInfoMetricPortMapping          = "Port Mapping"
	EthernetInfoMetricStateTogglingCounter = "State toggling counter"
	EthernetInfoMetricExternalLinkStatus   = "External Link Status"
	EthernetInfoMetricLinkStatus           = "Link Status"
	EthernetInfoMetricPHYStatus            = "PHY Status"
)

// Ethernet status metric names.
const (
	EthernetStatusMetricExternalLinkStatus     = "External Link Status"
	EthernetStatusMetricLinkStatus             = "Link Status"
	EthernetStatusMetricPHYStatus              = "PHY Status"
	EthernetStatusMetricPortMapping            = "Port Mapping"
	EthernetStatusMetricBERCorrectable         = "BER Correctable"
	EthernetStatusMetricBERUncorrectable       = "BER Uncorrectable"
	EthernetStatusMetricNack                   = "Nack"
	EthernetStatusMetricCRC                    = "CRC"
	EthernetStatusMetricRetransmissionTimeout  = "Retransmission Timeout"
	EthernetStatusMetricLinkRetrainingDueToBER = "Link retraining Due To BER"
	EthernetStatusMetricMACRemote              = "MAC Remote"
	EthernetStatusMetricRetransmission         = "Retransmission"
	EthernetStatusMetricRetraining             = "Retraining"
	EthernetStatusMetricSERPreFEC              = "SER preFEC"
	EthernetStatusMetricSERPostFEC             = "SER postFEC"
	EthernetStatusMetricLatency                = "Latency"
	EthernetStatusMetricThroughput             = "Throughput"
	EthernetStatusMetricStateTogglingCounter   = "State toggling counter"
)

// Frequency metric names.
const (
	FrequencyMetricHBMFrequency          = "HBM Frequency"
	FrequencyMetricMaxTPCFrequency       = "max TPC frequency"
	FrequencyMetricMaxMMEFrequency       = "max MME frequency"
	FrequencyMetricMaxDMAFrequency       = "max DMA frequency"
	FrequencyMetricMaxMediaFrequency     = "max Media frequency"
	FrequencyMetricMaxPCIeFrequency      = "max PCIe frequency"
	FrequencyMetricMaxARMFrequency       = "max ARM frequency"
	FrequencyMetricMaxNICFrequency       = "max NIC frequency"
	FrequencyMetricMaxNoCFrequency       = "max NoC frequency"
	FrequencyMetricCurrentTPCFrequency   = "current TPC frequency"
	FrequencyMetricCurrentMMEFrequency   = "current MME frequency"
	FrequencyMetricCurrentDMAFrequency   = "current DMA frequency"
	FrequencyMetricCurrentMediaFrequency = "current Media frequency"
	FrequencyMetricCurrentPCIeFrequency  = "current PCIe frequency"
	FrequencyMetricCurrentARMFrequency   = "current ARM frequency"
	FrequencyMetricCurrentNICFrequency   = "current NIC frequency"
	FrequencyMetricCurrentNoCFrequency   = "current NoC frequency"
	FrequencyMetricCurrentSRAMFrequency  = "current SRAM frequency"
	FrequencyMetricCurrentMSSFrequency   = "current MSS frequency"
)

// Hbm metric names.
const (
	HBMMetricEccErrors          = "ECC errors"
	HBMMetricNumOfRepairedLanes = "Number of repaired lanes"
	HBMMetricRepairedLanes      = "Repaired Lane"
	HBMMetricNumOfReplacedRows  = "Number of replaced rows"
	HBMMetricReplaceRows        = "Replaced row"
	HBMMetricMbistRepair        = "MBIST Repair"
	HBMMetricGlobalECC          = "Global ECC"
)

// Info metric names.
const (
	InfoMetricDeviceID          = "Device ID"
	InfoMetricSubsystemDeviceID = "Subsystem Device ID"
	InfoMetricSubsystemVendorID = "Subsystem Vendor ID"
	InfoMetricASICSerialNumber  = "ASIC Serial Number"
	InfoMetricBoardSerialNumber = "Board Serial Number"
	InfoMetricSRAMSize          = "SRAM size"
	InfoMetricHBMSize           = "HBM size"
	InfoMetricUUID              = "UUID"
)

// Pcie info metric names.
const (
	PcieInfoMetricMaxPCIeLinkSpeed                     = "Max PCIe Link Speed"
	PcieInfoMetricCurrentPCIeLinkSpeed                 = "Current PCIe Link Speed"
	PcieInfoMetricMaxPCIeLinkWidth                     = "Max PCIe Link Width"
	PcieInfoMetricCurrentPCIeLinkWidth                 = "Current PCIe Link Width"
	PcieInfoMetricPCIeDeviceID                         = "PCIe Device ID"
	PcieInfoMetricPCIeSubsystemID                      = "PCIe Subsystem ID"
	PcieInfoMetricPCIeSubsystemVendorID                = "PCIe Subsystem Vendor ID"
	PcieInfoMetricPCIeBusAndDevice                     = "PCIe Bus and Device"
	PcieInfoMetricCorrectedInternalErrorStatus         = "Corrected internal error status"
	PcieInfoMetricReplayBufferNumRolloverError         = "Replay buffer num rollover error"
	PcieInfoMetricReplayTimerTimeoutError              = "Replay timer timeout error"
	PcieInfoMetricBadTLPCounter                        = "Bad TLP counter"
	PcieInfoMetricBadDLLPCounter                       = "Bad DLLP counter"
	PcieInfoMetricReceiverErrorCounter                 = "Receiver error counter"
	PcieInfoMetricLCRCErrorCounter                     = "LCRC error counter"
	PcieInfoMetricECRCErrorCounter                     = "ECRC error counter"
	PcieInfoMetricCompletionTimeoutIndication          = "Completion timeout indication"
	PcieInfoMetricUncorrectableInternalErrorIndication = "Uncorrectable internal error indication"
	PcieInfoMetricReceiverOverflowIndication           = "Receiver overflow indication"
	PcieInfoMetricFlowControlProtocolErrorIndication   = "Flow control protocol error indication"
	PcieInfoMetricSurpriseLinkDownIndication           = "Surprise link down indication"
	PcieInfoMetricMalfunctionTLPErrorIndication        = "Malfunction TLP error indication"
	PcieInfoMetricDLLPProtocolErrorIndication          = "DLLP protocol error indication"
	PcieInfoMetricRXNakDLLPCounter                     = "RX Nak DLLP counter"
	PcieInfoMetricTxNakDLLPCounter                     = "Tx Nak DLLP counter"
	PcieInfoMetricRetryTLPcounter                      = "Retry TLP counter"
	PcieInfoMetricPWRBRKindication                     = "PWRBRK indication"
	PcieInfoMetricPCIeRXMemoryWriteCounter             = "PCIe RX memory write counter"
	PcieInfoMetricPCIeRXMemoryReadCounter              = "PCIe RX memory read counter"
	PcieInfoMetricPCIeTXMemoryWriteCounter             = "PCIe TX memory write counter"
	PcieInfoMetricPCIeTXMemoryReadCounter              = "PCIe TX memory read counter"
	PcieInfoMetricAERCapabilityControlOffset           = "AER capability control offset"
	PcieInfoMetricAERerrorlog                          = "AER error log"
	PcieInfoMetricPCIeFWversion                        = "PCIe FW version"
)

// Power metric names.
const (
	PowerMetricCurrentPowerConsumption = "Current Power Consumption"
	PowerMetricCurrentSOC12VPower      = "Current SOC 12V Power"
	PowerMetricCurrentSOC54VPower      = "Current SOC 54V Power"
	PowerMetricPeakPowerConsumption    = "Peak Power Consumption"
	PowerMetricPeakSOC12VPower         = "Peak SOC 12V Power"
	PowerMetricPeakSOC54VPower         = "Peak SOC 54V Power"
)

// Security metric names.
const (
	SecurityMetricCurrentPublicKeyHashIndex = "current public key hash index"
	SecurityMetricCurrentSVNversion         = "current SVN version"
	SecurityMetricKeyRevocation             = "key revocation"
	SecurityMetricKey0Revocation            = "key 0 revocation"
	SecurityMetricKey1Revocation            = "key 1 revocation"
	SecurityMetricKey2Revocation            = "key 2 revocation"
	SecurityMetricKey3Revocation            = "key 3 revocation"
	SecurityMetricKey4Revocation            = "key 4 revocation"
	SecurityMetricMinimalSVNindex           = "minimal SVN index"
	SecurityMetricFWImageSource             = "FW image source"
	SecurityMetricTPMPCRPPBOOT              = "TPM PCR PPBOOT"
	SecurityMetricTPMPCRPREBOOT             = "TPM PCR PREBOOT"
	SecurityMetricTPMPCRBOOT                = "TPM PCR BOOT"
	SecurityMetricTPMPCRLINUX               = "TPM PCR LINUX"
	SecurityMetricCPLDVersion               = "CPLD Version"
	SecurityMetricCPLDVersionTimestamp      = "CPLD Version timestamp"
)

// Sensor current metric names.
const (
	SensorCurrentVin54          = "54V in"
	SensorCurrentP1Vin12        = "12P1V in"
	SensorCurrentStage154Vin    = "Stage154V in"
	SensorCurrentStage113P5VOut = "Stage113P5V out"
	SensorCurrentStage213P5Vin  = "Stage213P5V in"
	SensorCurrentStage2CoreOut  = "Stage2 Core out"
	SensorCurrentStage2HBMout   = "Stage2 HBM out"
)

// Sensor temperature metric names.
const (
	SensorTemperatureMetricOnDie0    = "OnDie 0"
	SensorTemperatureMetricOnDie1    = "OnDie 1"
	SensorTemperatureMetricOnDie2    = "OnDie 2"
	SensorTemperatureMetricOnDie3    = "OnDie 3"
	SensorTemperatureMetricHBM0      = "HBM 0"
	SensorTemperatureMetricHBM1      = "HBM 1"
	SensorTemperatureMetricHBM2      = "HBM 2"
	SensorTemperatureMetricHBM3      = "HBM 3"
	SensorTemperatureMetricHBM4      = "HBM 4"
	SensorTemperatureMetricHBM5      = "HBM 5"
	SensorTemperatureMetricCPLDLocal = "CPLD local"
	SensorTemperatureMetricCPLD0     = "CPLD 0"
	SensorTemperatureMetricCPLD1     = "CPLD 1"
	SensorTemperatureMetricCPLD2     = "CPLD 2"
	SensorTemperatureMetricCPLD3     = "CPLD 3"
	SensorTemperatureMetricOnboard0  = "Onboard 0"
	SensorTemperatureMetricOnboard1  = "Onboard 1"
	SensorTemperatureMetricOnboard2  = "Onboard 2"
	SensorTemperatureMetricOnboard3  = "Onboard 3"
	SensorTemperatureMetricCPLDTemp  = "CPLD Temp"
	SensorTemperatureMetricPSUStage1 = "PSU Stage1"
	SensorTemperatureMetricPSUStage2 = "PSU Stage2"
)

// Sensor voltage monitor metric names.
const (
	SensorVoltageMonitorSwVm       = "SwVm"
	SensorVoltageMonitorSwCpeEu_0  = "SwCpeEu_0"
	SensorVoltageMonitorSwCpeEu_1  = "SwCpeEu_1"
	SensorVoltageMonitorSwCpeEu_2  = "SwCpeEu_2"
	SensorVoltageMonitorSwcpeEu_3  = "SwcpeEu_3"
	SensorVoltageMonitorSwCpeHbm   = "SwCpeHbm"
	SensorVoltageMonitorSwTpcSb    = "SwTpcSb"
	SensorVoltageMonitorSwTft      = "SwTft"
	SensorVoltageMonitorSwCnt      = "SwCnt"
	SensorVoltageMonitorSwMcHbm0_0 = "SwMcHbm0_0"
	SensorVoltageMonitorSwMcHbm0_1 = "SwMcHbm0_1"
	SensorVoltageMonitorSwHconHbm0 = "SwHconHbm0"
	SensorVoltageMonitorSwPpw_0    = "SwPpw_0"
	SensorVoltageMonitorSwPpw_1    = "SwPpw_1"
	SensorVoltageMonitorSwL2cMacro = "SwL2cMacro"
	SensorVoltageMonitorSwVcdMacro = "SwVcdMacro"
	SensorVoltageMonitorSeVm       = "SeVm"
	SensorVoltageMonitorSePe0_0    = "SePe0_0"
	SensorVoltageMonitorSePe0_1    = "SePe0_1"
	SensorVoltageMonitorSeEuCore   = "SeEuCore"
	SensorVoltageMonitorSeBpyramid = "SeBpyramid"
	SensorVoltageMonitorSeRx       = "SeRx"
	SensorVoltageMonitorSeMx       = "SeMx"
	SensorVoltageMonitorSeHconHbm1 = "SeHconHbm1"
	SensorVoltageMonitorSeMcHbm1   = "SeMcHbm1"
	SensorVoltageMonitorSeGasket   = "SeGasket"
	SensorVoltageMonitorSeMmeCtrl  = "SeMmeCtrl"
	SensorVoltageMonitorSeMmeQman  = "SeMmeQman"
	SensorVoltageMonitorSeSbte     = "SeSbte"
	SensorVoltageMonitorSeRtrDn    = "SeRtrDn"
	SensorVoltageMonitorSeRtrUp    = "SeRtrUp"
	SensorVoltageMonitorSeSram     = "SeSram"
	SensorVoltageMonitorNwVm       = "NwVm"
	SensorVoltageMonitorNwPe0_0    = "NwPe0_0"
	SensorVoltageMonitorNwPe0_1    = "NwPe0_1"
	SensorVoltageMonitorNwPe0_2    = "NwPe0_2"
	SensorVoltageMonitorNwPe0_3    = "NwPe0_3"
	SensorVoltageMonitorNwEuCore   = "NwEuCore"
	SensorVoltageMonitorNwBpyramid = "NwBpyramid"
	SensorVoltageMonitorNwMcHbm4_0 = "NwMcHbm4_0"
	SensorVoltageMonitorNwMcHbm4_1 = "NwMcHbm4_1"
	SensorVoltageMonitorNwHconHbm4 = "NwHconHbm4"
	SensorVoltageMonitorNwAcc      = "NwAcc"
	SensorVoltageMonitorNwWap      = "NwWap"
	SensorVoltageMonitorNwTif      = "NwTif"
	SensorVoltageMonitorNwRtrDn    = "NwRtrDn"
	SensorVoltageMonitorNwRtrUp    = "NwRtrUp"
	SensorVoltageMonitorNwSram     = "NwSram"
	SensorVoltageMonitorNeVM       = "NeVM"
	SensorVoltageMonitorNeTx       = "NeTx"
	SensorVoltageMonitorNeMx_0     = "NeMx_0"
	SensorVoltageMonitorNeMx_1     = "NeMx_1"
	SensorVoltageMonitorNeHconHbm5 = "NeHconHbm5"
	SensorVoltageMonitorNeMcHbm5   = "NeMcHbm5"
	SensorVoltageMonitorNeSob      = "NeSob"
	SensorVoltageMonitorNeQnt      = "NeQnt"
	SensorVoltageMonitorNeCnt_0    = "NeCnt_0"
	SensorVoltageMonitorNeCnt_1    = "NeCnt_1"
	SensorVoltageMonitorNeCpeEu    = "NeCpeEu"
	SensorVoltageMonitorNeCntHbm   = "NeCntHbm"
	SensorVoltageMonitorNeSbte_0   = "NeSbte_0"
	SensorVoltageMonitorNeSbte_1   = "NeSbte_1"
	SensorVoltageMonitorNeMif      = "NeMif"
	SensorVoltageMonitorNeRtrDn    = "NeRtrDn"
)

// Sensor voltage metric names.
const (
	SensorVoltageVADC54          = "54VADC"
	SensorVoltageVRM1in          = "VRM1 in"
	SensorVoltageVRM1out         = "VRM1 out"
	SensorVoltageVRM2in          = "VRM2 in"
	SensorVoltageVRM2VDDout      = "VRM2 VDD out"
	SensorVoltageVRM2HBMout      = "VRM2 HBM out"
	SensorVoltageVMONPCIEVPH1P8V = "VMON PCIE VPH 1P8V"
	SensorVoltageVMON1P8HBMVAA   = "VMON 1P8 HBM VAA"
	SensorVoltageVMON2P5         = "VMON 2P5"
	SensorVoltageVMON48VHIMON    = "VMON 48V HIMON"
	SensorVoltageVMONP5V         = "VMON P5V"
	SensorVoltageVMON12V1        = "VMON 12V1"
	SensorVoltageVMONHBM         = "VMON HBM"
	SensorVoltageVMONCore        = "VMON Core"
	SensorVoltageCPLDHIMON1P8NIC = "CPLD HIMON 1P8NIC"
)

// Status metric names.
const (
	StatusMetricBootStage                    = "Boot Stage"
	StatusMetricEmergencyPowerReduction      = "Emergency Power Reduction"
	StatusMetricClockThrottling              = "Clock Throttling"
	StatusMetricLastClockThrottlingDuration  = "Last Clock Throttling duration"
	StatusMetricPowerState                   = "Power State"
	StatusMetricTotalClockThrottlingDuration = "Total Clock Throttling duration"
	StatusMetricGlobalTimeFromReset          = "Global Time from Reset"
	StatusMetricChipStatus                   = "Chip Status"
	StatusMetricDeviceActivity               = "Device Activity"
	StatusMetricDeviceActivityCounter        = "Device Activity counter"
	StatusMetricDevicePowerReduction         = "Device Power Reduction"
	StatusMetricLastPowerReductionDuration   = "Last Power Reduction Duration"
)

// Temperature metric names.
const (
	TemperatureMetricCurrentBoardTemp               = "Current Board Temperature"
	TemperatureMetricCurrentVRMTemp                 = "Current VRM Temperature"
	TemperatureMetricCurrentDRAMTemp                = "Current DRAM Temperature"
	TemperatureMetricCurrentOnDieTemp               = "Current On-die Temperature"
	TemperatureMetricCurrentSocTemp                 = "Current SOC Temperature"
	TemperatureMetricCurrentHBMTemp                 = "Current HBM Temperature"
	TemperatureMetricHistoricalBoardTemp            = "Historical Board Temperature"
	TemperatureMetricHistoricalVRMTemp              = "Historical VRM Temperature"
	TemperatureMetricHistoricalDRAMTemp             = "Historical DRAM Temperature"
	TemperatureMetricHistoricalOnDieTemp            = "Historical On-die Temperature"
	TemperatureMetricHistoricalSocTemp              = "Historical SOC Temperature"
	TemperatureMetricHistoricalHBMTemp              = "Historical HBM Temperature"
	TemperatureMetricMaxTempRiseTime                = "Max Temperature rise time"
	TemperatureMetricMaxSocTempErrorThreshold       = "Max SOC Temperature error Threshold"
	TemperatureMetricMaxSocTempWarmingThreshold     = "Max SOC Temperature warning Threshold"
	TemperatureMetricMaxHbmTempThreshold            = "Max HBM Temperature Threshold"
	TemperatureMetricCurrentSocTempErrorThreshold   = "Current SOC Temperature error Threshold"
	TemperatureMetricCurrentSocTempWarningThreshold = "Current SOC Temperature warning Threshold"
	TemperatureMetricCurrentHbmTempThreshold        = "Current HBM Temperature Threshold"
)

// Lane info metric names
const (
	LaneInfoMetricEBUFOverflow        = "EBUF Overflow"
	LaneInfoMetricEBUFUnderRun        = "EBUF Under Run"
	LaneInfoMetricDecodeError         = "Decode Error"
	LaneInfoMetricRunningDisplayError = "Running Display Error"
	LaneInfoMetricSKPOSParityError    = "SKPOS Parity Error"
	LaneInfoMetricSYNCHeaderError     = "SYNC Header Error"
	LaneInfoMetricDeskewError         = "Deskew Error"
)

// Alerts types.
const (
	AlertTypeDoubleECCBlockErr                     = "DOUBLE_ECC_BLOCK_ERR"
	AlertTypeSingleECCBlockErr                     = "SINGLE_ECC_BLOCK_ERR"
	AlertTypeHBMCommandAddressErr                  = "HBM_COMMAND_ADDRESS_ERR"
	AlertTypeHBMDataWriteErr                       = "HBM_DATA_WRITE_ERR"
	AlertTypeHBMDataReadErr                        = "HBM_DATA_READ_ERR"
	AlertTypeDoubleECCErr                          = "DOUBLE_ECC_ERR" /* 5 */
	AlertTypeSingleECCErr                          = "SINGLE_ECC_ERR"
	AlertTypeSramUnrepairableRingsErr              = "SRAM_UNREPAIRABLE_RINGS_ERR"
	AlertTypeSramRepairedRingsErr                  = "SRAM_REPAIRED_RINGS_ERR"
	AlertTypeHbmCatastrophicTempErr                = "HBM_CATASTROPHIC_TEMP_ERR"
	AlertTypePcieUncorrectableFatalErr             = "PCIE_UNCORRECTABLE_FATAL_ERR" /* 10 */
	AlertTypePcieReceiverOverflowErr               = "PCIE_RECEIVER_OVERFLOW_ERR"
	AlertTypePcieFlowControlProtocolErr            = "PCIE_FLOW_CONTROL_PROTOCOL_ERR"
	AlertTypePcieSurpriseLinkDownErr               = "PCIE_SURPRISE_LINK_DOWN_ERR"
	AlertTypePcieMalfunctionTlpErr                 = "PCIE_MALFUNCTION_TLP_ERR"
	AlertTypePcieDllpProtocolErr                   = "PCIE_DLLP_PROTOCOL_ERR" /* 15 */
	AlertTypePcieEcrcErr                           = "PCIE_ECRC_ERR"
	AlertTypePcieCompletionTimeoutErr              = "PCIE_COMPLETION_TIMEOUT_ERR"
	AlertTypePcieCorrectedInternalErr              = "PCIE_CORRECTED_INTERNAL_ERR"
	AlertTypePcieReplayBufferRolloverErr           = "PCIE_REPLAY_BUFFER_ROLLOVER_ERR"
	AlertTypePcieReplayTimerTimeoutErr             = "PCIE_REPLAY_TIMER_TIMEOUT_ERR" /* 20 */
	AlertTypePcieBadDllpErr                        = "PCIE_BAD_DLLP_ERR"
	AlertTypePcieBadTlpErr                         = "PCIE_BAD_TLP_ERR"
	AlertTypePcieReceiverErr                       = "PCIE_RECEIVER_ERR"
	AlertTypePcieLcrdErr                           = "PCIE_LCRD_ERR"
	AlertTypePcieRxNakDllpErr                      = "PCIE_RX_NAK_DLLP_ERR" /* 25 */
	AlertTypePcieTxNakDllpErr                      = "PCIE_TX_NAK_DLLP_ERR"
	AlertTypePcieRetryTlpErr                       = "PCIE_RETRY_TLP_ERR"
	AlertTypeNicHighBerErr                         = "NIC_BER_ERR"
	AlertTypeNicMultipleNackErr                    = "NIC_MULTIPLE_NACK_ERR"
	AlertTypeNicMultipleCrcErr                     = "NIC_MULTIPLE_CRC_ERR" /* 30 */
	AlertTypeNicMultipleLinkReInitializationsErr   = "NIC_MULTIPLE_LINK_RE_INITIALIZATIONS_ERR"
	AlertTypeNicMultipleLinkReTransmissionsErr     = "NIC_MULTIPLE_LINK_RE_TRANSMISSIONS_ERR"
	AlertTypeThermalThresholdCrossingErr           = "THERMAL_THRESHOLD_CROSSING_ERR"
	AlertTypeThermalTempRiseTimeViolationErr       = "THERMAL_TEMP_RISE_TIME_VIOLATION_ERR"
	AlertTypeVoltageMonitorThreshold1Err           = "VOLTAGE_MONITOR_THRESHOLD_1_ERR" /* 35 */
	AlertTypeVoltageMonitorThreshold2Err           = "VOLTAGE_MONITOR_THRESHOLD_2_ERR"
	AlertTypeSecuritySpiRevokedPubKeyErr           = "SECURITY_SPI_REVOKED_PUB_KEY_ERR"
	AlertTypeSecuritySpiSvnErr                     = "SECURITY_SPI_SVN_ERR"
	AlertTypeSecuritySpiSignatureErr               = "SECURITY_SPI_SIGNATURE_ERR"
	AlertTypeSecurityAgentRevokedPubKeyErr         = "SECURITY_AGENT_REVOKED_PUB_KEY_ERR" /* 40 */
	AlertTypeSecurityAgentSvnErr                   = "SECURITY_AGENT_SVN_ERR"
	AlertTypeSecurityAgentSignatureErr             = "SECURITY_AGENT_SIGNATURE_ERR"
	AlertTypeSecurityAgentUbootErr                 = "SECURITY_AGENT_UBOOT_ERR"
	AlertTypeSecurityAgentLinuxErr                 = "SECURITY_AGENT_LINUX_ERR"
	AlertTypeSecurityAgentZephyrErr                = "SECURITY_AGENT_ZEPHYR_ERR" /* 45 */
	AlertTypeSecurityRevokeLastKeyErr              = "SECURITY_REVOKE_LAST_KEY_ERR"
	AlertTypeSecurityPermissionAccessErr           = "SECURITY_PERMISSION_ACCESS_ERR"
	AlertTypeWdHeartbeatErr                        = "WD_HEARTBEAT_ERR"
	AlertTypeWdTdrErr                              = "WD_TDR_ERR"
	AlertTypeWdHwErr                               = "WD_HW_ERR" /* 50 */
	AlertTypeChecksumPpbootPrimaryErr              = "CHECKSUM_PPBOOT_PRIMARY_ERR"
	AlertTypeChecksumPpbootSecondaryErr            = "CHECKSUM_PPBOOT_SECONDARY_ERR"
	AlertTypeChecksumPrebootPrimaryErr             = "CHECKSUM_PREBOOT_PRIMARY_ERR"
	AlertTypeChecksumPrebootSecondaryErr           = "CHECKSUM_PREBOOT_SECONDARY_ERR"
	AlertTypeChecksumCpldErr                       = "CHECKSUM_CPLD_ERR" /* 55 */
	AlertTypeChecksumHbmRmaPerityErr               = "CHECKSUM_HBM_RMA_PERITY_ERR"
	AlertTypeChecksumHbmRmaEccErr                  = "CHECKSUM_HBM_RMA_ECC_ERR"
	AlertTypeChecksumHbmRmaSramEccErr              = "CHECKSUM_HBM_RMA_SRAM_ECC_ERR"
	AlertTypeChecksumHbmRmaRowReplacementErr       = "CHECKSUM_HBM_RMA_ROW_REPLACEMENT_ERR"
	AlertTypeChecksumHbmRmaCauseErr                = "CHECKSUM_HBM_RMA_CAUSE_ERR" /* 60 */
	AlertTypeChecksumHbmRmaSpareRowAvailabilityErr = "CHECKSUM_HBM_RMA_SPARE_ROW_AVAILABILITY_ERR"
	AlertTypeFitInvalidImageFormatErr              = "FIT_INVALID_IMAGE_FORMAT_ERR"
	AlertTypeFitTargetAddreesErr                   = "FIT_TARGET_ADDREES_ERR"
	AlertTypeFitNotRunableErr                      = "FIT_NOT_RUNABLE_ERR"
	AlertTypePowerThresholdCrossingErr             = "POWER_THRESHOLD_CROSSING_ERR"
	AlertTypeFatalSramEccErr                       = "FATAL_SRAM_ECC_ERR"
	AlertTypeFatalHbmEccErr                        = "FATAL_HBM_ECC_ERR"
	AlertTypeFatalHbmParityErr                     = "FATAL_HBM_PARITY_ERR"
	AlertTypeFatalHbmInitErr                       = "FATAL_HBM_INIT_ERR"
	AlertTypeFatalRowReplacementErr                = "FATAL_ROW_REPLACEMENT_ERR"
	AlertTypeHbmMbistRepairFailureErr              = "HBM_MBIST_REPAIR_FAILURE_ERR"
	AlertTypeVoltageMonitorThreshold               = "VOLTAGE_MONITOR_THRESHOLD"
	AlertTypeChecksumEepromDeviceAccessErr         = "CHECKSUM_EEPROM_DEVICE_ACCESS_ERR"
	AlertTypeChecksumEepromCrcErr                  = "CHECKSUM_EEPROM_CRC_ERR"
	AlertTypeChecksumEepromUnknownErr              = "CHECKSUM_EEPROM_UNKNOWN_ERR"
	AlertTypeDynamicRowReplacementErr              = "DYNAMIC_ROW_REPLACEMENT_ERR"
	AlertTypePllLockErr                            = "PLL_LOCK_ERR"
	AlertTypeDoubleEccCounterErr                   = "DOUBLE_ECC_COUNTER_ERR"
	AlertTypeSingleEccCounterErr                   = "SINGLE_ECC_COUNTER_ERR"
	AlertTypeDoubleHbmCounterErr                   = "DOUBLE_HBM_COUNTER_ERR"
	AlertTypeSingleHbmCounterErr                   = "SINGLE_HBM_COUNTER_ERR"
)
