// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/bmc-monitoring/bmc-monitoring.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	bmcmonitoring "habana_bmc_exporter/pkg/bmc-monitoring"
	reflect "reflect"

	logrus "github.com/sirupsen/logrus"
	gomock "go.uber.org/mock/gomock"
)

// MockExporter is a mock of Exporter interface.
type MockExporter struct {
	ctrl     *gomock.Controller
	recorder *MockExporterMockRecorder
}

// MockExporterMockRecorder is the mock recorder for MockExporter.
type MockExporterMockRecorder struct {
	mock *MockExporter
}

// NewMockExporter creates a new mock instance.
func NewMockExporter(ctrl *gomock.Controller) *MockExporter {
	mock := &MockExporter{ctrl: ctrl}
	mock.recorder = &MockExporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExporter) EXPECT() *MockExporterMockRecorder {
	return m.recorder
}

// Alerts mocks base method.
func (m *MockExporter) Alerts(arg0 context.Context, arg1 bmcmonitoring.AlertsData, arg2 *logrus.Entry) []bmcmonitoring.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Alerts", arg0, arg1, arg2)
	ret0, _ := ret[0].([]bmcmonitoring.Metric)
	return ret0
}

// Alerts indicates an expected call of Alerts.
func (mr *MockExporterMockRecorder) Alerts(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Alerts", reflect.TypeOf((*MockExporter)(nil).Alerts), arg0, arg1, arg2)
}

// BmcState mocks base method.
func (m *MockExporter) BmcState(arg0 context.Context, arg1 *logrus.Entry) []bmcmonitoring.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BmcState", arg0, arg1)
	ret0, _ := ret[0].([]bmcmonitoring.Metric)
	return ret0
}

// BmcState indicates an expected call of BmcState.
func (mr *MockExporterMockRecorder) BmcState(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BmcState", reflect.TypeOf((*MockExporter)(nil).BmcState), arg0, arg1)
}

// CTemperature mocks base method.
func (m *MockExporter) CTemperature(arg0 context.Context, arg1 *logrus.Entry) []bmcmonitoring.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CTemperature", arg0, arg1)
	ret0, _ := ret[0].([]bmcmonitoring.Metric)
	return ret0
}

// CTemperature indicates an expected call of CTemperature.
func (mr *MockExporterMockRecorder) CTemperature(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CTemperature", reflect.TypeOf((*MockExporter)(nil).CTemperature), arg0, arg1)
}

// DeleteAllTokens mocks base method.
func (m *MockExporter) DeleteAllTokens(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllTokens", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllTokens indicates an expected call of DeleteAllTokens.
func (mr *MockExporterMockRecorder) DeleteAllTokens(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllTokens", reflect.TypeOf((*MockExporter)(nil).DeleteAllTokens), arg0)
}

// Direct mocks base method.
func (m *MockExporter) Direct(arg0 context.Context, arg1 *logrus.Entry) []bmcmonitoring.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Direct", arg0, arg1)
	ret0, _ := ret[0].([]bmcmonitoring.Metric)
	return ret0
}

// Direct indicates an expected call of Direct.
func (mr *MockExporterMockRecorder) Direct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Direct", reflect.TypeOf((*MockExporter)(nil).Direct), arg0, arg1)
}

// EthernetInfo mocks base method.
func (m *MockExporter) EthernetInfo(arg0 context.Context, arg1 *logrus.Entry) []bmcmonitoring.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EthernetInfo", arg0, arg1)
	ret0, _ := ret[0].([]bmcmonitoring.Metric)
	return ret0
}

// EthernetInfo indicates an expected call of EthernetInfo.
func (mr *MockExporterMockRecorder) EthernetInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EthernetInfo", reflect.TypeOf((*MockExporter)(nil).EthernetInfo), arg0, arg1)
}

// EthernetStatus mocks base method.
func (m *MockExporter) EthernetStatus(arg0 context.Context, arg1 *logrus.Entry) []bmcmonitoring.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EthernetStatus", arg0, arg1)
	ret0, _ := ret[0].([]bmcmonitoring.Metric)
	return ret0
}

// EthernetStatus indicates an expected call of EthernetStatus.
func (mr *MockExporterMockRecorder) EthernetStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EthernetStatus", reflect.TypeOf((*MockExporter)(nil).EthernetStatus), arg0, arg1)
}

// EthernetStatusCounters mocks base method.
func (m *MockExporter) EthernetStatusCounters(arg0 context.Context, arg1 *logrus.Entry) []bmcmonitoring.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EthernetStatusCounters", arg0, arg1)
	ret0, _ := ret[0].([]bmcmonitoring.Metric)
	return ret0
}

// EthernetStatusCounters indicates an expected call of EthernetStatusCounters.
func (mr *MockExporterMockRecorder) EthernetStatusCounters(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EthernetStatusCounters", reflect.TypeOf((*MockExporter)(nil).EthernetStatusCounters), arg0, arg1)
}

// Frequency mocks base method.
func (m *MockExporter) Frequency(arg0 context.Context, arg1 *logrus.Entry) []bmcmonitoring.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Frequency", arg0, arg1)
	ret0, _ := ret[0].([]bmcmonitoring.Metric)
	return ret0
}

// Frequency indicates an expected call of Frequency.
func (mr *MockExporterMockRecorder) Frequency(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Frequency", reflect.TypeOf((*MockExporter)(nil).Frequency), arg0, arg1)
}

// Hbm mocks base method.
func (m *MockExporter) Hbm(arg0 context.Context, arg1 *logrus.Entry) []bmcmonitoring.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hbm", arg0, arg1)
	ret0, _ := ret[0].([]bmcmonitoring.Metric)
	return ret0
}

// Hbm indicates an expected call of Hbm.
func (mr *MockExporterMockRecorder) Hbm(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hbm", reflect.TypeOf((*MockExporter)(nil).Hbm), arg0, arg1)
}

// Info mocks base method.
func (m *MockExporter) Info(arg0 context.Context, arg1 *logrus.Entry) []bmcmonitoring.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Info", arg0, arg1)
	ret0, _ := ret[0].([]bmcmonitoring.Metric)
	return ret0
}

// Info indicates an expected call of Info.
func (mr *MockExporterMockRecorder) Info(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockExporter)(nil).Info), arg0, arg1)
}

// LaneInfo mocks base method.
func (m *MockExporter) LaneInfo(arg0 context.Context, arg1 *logrus.Entry) []bmcmonitoring.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LaneInfo", arg0, arg1)
	ret0, _ := ret[0].([]bmcmonitoring.Metric)
	return ret0
}

// LaneInfo indicates an expected call of LaneInfo.
func (mr *MockExporterMockRecorder) LaneInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LaneInfo", reflect.TypeOf((*MockExporter)(nil).LaneInfo), arg0, arg1)
}

// Logout mocks base method.
func (m *MockExporter) Logout() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout")
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockExporterMockRecorder) Logout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockExporter)(nil).Logout))
}

// Name mocks base method.
func (m *MockExporter) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockExporterMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockExporter)(nil).Name))
}

// PcieInfo mocks base method.
func (m *MockExporter) PcieInfo(arg0 context.Context, arg1 *logrus.Entry) []bmcmonitoring.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PcieInfo", arg0, arg1)
	ret0, _ := ret[0].([]bmcmonitoring.Metric)
	return ret0
}

// PcieInfo indicates an expected call of PcieInfo.
func (mr *MockExporterMockRecorder) PcieInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PcieInfo", reflect.TypeOf((*MockExporter)(nil).PcieInfo), arg0, arg1)
}

// Power mocks base method.
func (m *MockExporter) Power(arg0 context.Context, arg1 *logrus.Entry) []bmcmonitoring.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Power", arg0, arg1)
	ret0, _ := ret[0].([]bmcmonitoring.Metric)
	return ret0
}

// Power indicates an expected call of Power.
func (mr *MockExporterMockRecorder) Power(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Power", reflect.TypeOf((*MockExporter)(nil).Power), arg0, arg1)
}

// RMA mocks base method.
func (m *MockExporter) RMA(arg0 context.Context, arg1 *logrus.Entry) []bmcmonitoring.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RMA", arg0, arg1)
	ret0, _ := ret[0].([]bmcmonitoring.Metric)
	return ret0
}

// RMA indicates an expected call of RMA.
func (mr *MockExporterMockRecorder) RMA(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RMA", reflect.TypeOf((*MockExporter)(nil).RMA), arg0, arg1)
}

// RefreshToken mocks base method.
func (m *MockExporter) RefreshToken(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockExporterMockRecorder) RefreshToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockExporter)(nil).RefreshToken), arg0)
}

// Security mocks base method.
func (m *MockExporter) Security(arg0 context.Context, arg1 *logrus.Entry) []bmcmonitoring.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Security", arg0, arg1)
	ret0, _ := ret[0].([]bmcmonitoring.Metric)
	return ret0
}

// Security indicates an expected call of Security.
func (mr *MockExporterMockRecorder) Security(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Security", reflect.TypeOf((*MockExporter)(nil).Security), arg0, arg1)
}

// SensorCurrent mocks base method.
func (m *MockExporter) SensorCurrent(arg0 context.Context, arg1 *logrus.Entry) []bmcmonitoring.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SensorCurrent", arg0, arg1)
	ret0, _ := ret[0].([]bmcmonitoring.Metric)
	return ret0
}

// SensorCurrent indicates an expected call of SensorCurrent.
func (mr *MockExporterMockRecorder) SensorCurrent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SensorCurrent", reflect.TypeOf((*MockExporter)(nil).SensorCurrent), arg0, arg1)
}

// SensorTemperature mocks base method.
func (m *MockExporter) SensorTemperature(arg0 context.Context, arg1 *logrus.Entry) []bmcmonitoring.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SensorTemperature", arg0, arg1)
	ret0, _ := ret[0].([]bmcmonitoring.Metric)
	return ret0
}

// SensorTemperature indicates an expected call of SensorTemperature.
func (mr *MockExporterMockRecorder) SensorTemperature(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SensorTemperature", reflect.TypeOf((*MockExporter)(nil).SensorTemperature), arg0, arg1)
}

// SensorVoltage mocks base method.
func (m *MockExporter) SensorVoltage(arg0 context.Context, arg1 *logrus.Entry) []bmcmonitoring.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SensorVoltage", arg0, arg1)
	ret0, _ := ret[0].([]bmcmonitoring.Metric)
	return ret0
}

// SensorVoltage indicates an expected call of SensorVoltage.
func (mr *MockExporterMockRecorder) SensorVoltage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SensorVoltage", reflect.TypeOf((*MockExporter)(nil).SensorVoltage), arg0, arg1)
}

// SensorVoltageMonitor mocks base method.
func (m *MockExporter) SensorVoltageMonitor(arg0 context.Context, arg1 *logrus.Entry) []bmcmonitoring.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SensorVoltageMonitor", arg0, arg1)
	ret0, _ := ret[0].([]bmcmonitoring.Metric)
	return ret0
}

// SensorVoltageMonitor indicates an expected call of SensorVoltageMonitor.
func (mr *MockExporterMockRecorder) SensorVoltageMonitor(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SensorVoltageMonitor", reflect.TypeOf((*MockExporter)(nil).SensorVoltageMonitor), arg0, arg1)
}

// Status mocks base method.
func (m *MockExporter) Status(arg0 context.Context, arg1 *logrus.Entry) []bmcmonitoring.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", arg0, arg1)
	ret0, _ := ret[0].([]bmcmonitoring.Metric)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockExporterMockRecorder) Status(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockExporter)(nil).Status), arg0, arg1)
}

// Temperature mocks base method.
func (m *MockExporter) Temperature(arg0 context.Context, arg1 *logrus.Entry) []bmcmonitoring.Metric {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Temperature", arg0, arg1)
	ret0, _ := ret[0].([]bmcmonitoring.Metric)
	return ret0
}

// Temperature indicates an expected call of Temperature.
func (mr *MockExporterMockRecorder) Temperature(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Temperature", reflect.TypeOf((*MockExporter)(nil).Temperature), arg0, arg1)
}

// ValidToken mocks base method.
func (m *MockExporter) ValidToken(arg0 context.Context, arg1 *logrus.Entry) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidToken", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// ValidToken indicates an expected call of ValidToken.
func (mr *MockExporterMockRecorder) ValidToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidToken", reflect.TypeOf((*MockExporter)(nil).ValidToken), arg0, arg1)
}
