{
 "title": "HABANA.AI / BMC / Cluster (BMC) g3",
 "tags": [ "habana.ai/bmc" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Alerts",
   "type": "stat",
   "description": "BMC Alerts counter",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# 1. sum over time the number of alerts\r\n# 2. count the alerts by hosts\r\n# 3. count the number of hosts that we have alerts on\r\n\r\ncount (count (sum_over_time (habana_bmc_alerts[$__range])) by (oam, hostname))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total BMC",
   "type": "stat",
   "description": "BMC Alerts counter",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(habana_bmc_state)" }
   ]
  },
  {
   "title": "Offline BMC",
   "type": "stat",
   "description": "BMC Alerts counter",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(habana_bmc_state == 0)" }
   ]
  },
  {
   "title": "Exporter API Version",
   "type": "stat",
   "description": "BMC Alerts counter",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "habana_bmc_exporter_info", "legendFormat": "{{ exporter_version }}" }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "habana_bmc_alerts",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Ethernet - Port Counter",
   "type": "timeseries",
   "description": "Port Counter - Up/down",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (habana_bmc_ethernet_status_state_toggling_counter) by (hostname) ",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Device - OAM Activity",
   "type": "timeseries",
   "description": "Count Device Activity per OAM \ne.g: 8 = 8 cards in used",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(habana_bmc_status_device_activity) by (hostname)",
     "legendFormat": "oam{{hostname}}"
    }
   ]
  },
  {
   "title": "Power -  Current Power (OAMs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "expr": "sum(habana_bmc_power_current_power_consumption) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}