{
 "title": "HABANA.AI / BMC / Node (OAM) g3",
 "tags": [ "habana.ai/bmc" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "hostname",
    "query": {
     "query": "label_values(habana_bmc_state,hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OAM  Info",
   "type": "table",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(habana_bmc_info_asic_serial_number{hostname=~\"$hostname\"}) by (oam, asic_serial_number)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(habana_bmc_info_board_serial_number{hostname=~\"$hostname\"}) by (oam, board_serial_number)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(habana_bmc_info_device_id{hostname=~\"$hostname\"}) by (oam, device_id)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(habana_bmc_info_uuid{hostname=~\"$hostname\"}) by (oam, uuid)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(habana_bmc_info_subsystem_vendor_id{hostname=~\"$hostname\"}) by (oam, subsystem_vendor_id)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(habana_bmc_security_cpld_version{hostname=~\"$hostname\"}) by (oam, cpld_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "BMC up/Down",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(habana_bmc_state{hostname=~\"$hostname\"})"
    }
   ]
  },
  {
   "title": "OAM Device Activity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(habana_bmc_status_device_activity{hostname=~\"$hostname\"}) by (oam)",
     "legendFormat": "oam{{oam}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "BMC Uptime",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(habana_bmc_state{hostname=~\"$hostname\"})"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "description": "BMC Alerts counter",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# 1. sum over time the number of alerts\r\n# 2. count the alerts by hosts\r\n# 3. count the number of hosts that we have alerts on\r\n\r\ncount (count (sum_over_time (habana_bmc_alerts{hostname=~\"$hostname\"}[$__range]) != 0) by (oam, hostname))"
    }
   ]
  },
  {
   "title": "OAM Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "OAM  Info",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(habana_bmc_info_asic_serial_number{hostname=~\"$hostname\"}) by (oam, asic_serial_number)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(habana_bmc_info_board_serial_number{hostname=~\"$hostname\"}) by (oam, board_serial_number)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(habana_bmc_info_device_id{hostname=~\"$hostname\"}) by (oam, device_id)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(habana_bmc_info_hbm_size{hostname=~\"$hostname\"}) by (oam)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(habana_bmc_info_sram_size{hostname=~\"$hostname\"}) by (oam)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(habana_bmc_info_uuid{hostname=~\"$hostname\"}) by (oam, uuid)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(habana_bmc_info_subsystem_device_id{hostname=~\"$hostname\"}) by (oam, subsystem_device_id)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(habana_bmc_info_subsystem_vendor_id{hostname=~\"$hostname\"}) by (oam, subsystem_vendor_id)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(habana_bmc_security_cpld_version{hostname=~\"$hostname\"}) by (oam, cpld_version)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "OAM Alert", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "habana_bmc_alerts{hostname=~\"$hostname\"} != 0",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "OAM Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Current Power - SOC 12V",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "expr": "avg(habana_bmc_power_current_soc_12v_power{hostname=~\"$hostname\"}) by (oam)",
     "legendFormat": "oam{{oam}}"
    }
   ]
  },
  {
   "title": "Peak Power - SOC 12V",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "expr": "habana_bmc_power_peak_soc_12v_power{hostname=~\"$hostname\"}",
     "legendFormat": "oam{{oam}}"
    }
   ]
  },
  {
   "title": "Current Power - SOC 54V",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "expr": "avg(habana_bmc_power_current_soc_54v_power{hostname=~\"$hostname\"}) by (oam)",
     "legendFormat": "oam{{oam}}"
    }
   ]
  },
  {
   "title": "Peak Power - SOC 54V",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "expr": "habana_bmc_power_peak_soc_54v_power{hostname=~\"$hostname\"}",
     "legendFormat": "oam{{oam}}"
    }
   ]
  },
  { "title": "OAM Sensors Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "HBM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(habana_bmc_temperature_current_hbm_temperature{hostname=~\"$hostname\"}) by (oam)",
     "legendFormat": "oam{{oam}}"
    }
   ]
  },
  {
   "title": "SOC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(habana_bmc_temperature_current_soc_temperature{hostname=~\"$hostname\"}) by (oam)",
     "legendFormat": "oam{{oam}}"
    }
   ]
  },
  { "title": "OAM Ctemperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Ctemperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(habana_bmc_ctemperature{hostname=~\"$hostname\"}) by (oam)",
     "legendFormat": "oam{{oam}}"
    }
   ]
  }
 ]
}